# Generated by Django 5.0.4 on 2024-04-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='addresses',
            field=models.ManyToManyField(blank=True, null=True, to='users.address'),
        ),
    ]
